---

# all
# ansible_vmware_validate_certs: no
# ansible_connection: ssh
# #ansible_connection: vmware_tools
# ansible_vmware_guest_path: "DC1/vm/"
# vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
# vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
# vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"

# rhel
vm_name: rhel-1
vm_template: rhel94-tpl
vm_datacenter: SDDC-Datacenter
vm_cluster: Cluster-1
vm_datastore: workload_share_dwPsq
vm_folder: Workloads/sandbox-b8jvq  # needs to be changed for every deployment
#vm_folder: Cluster-1/sandbox-b8jvq  # needs to be changed for every deployment
vm_cpu: 1
vm_ram: 4096

vm_ip: 192.168.1.41
